kind: source
spec:
  name: "cloudquery"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ["postgresql"]
  spec:
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  registry: cloudquery
  version: "v6.1.3"
  write_mode: "append"
  spec:
    connection_string: postgresql://cq:password123@localhost:5432/cq-test?sslmode=disable
